#!/bin/bash

# READ NAME ARGUMENT OR PROMPT FOR NAME IF NONE PROVIDED

msg='\e[35m░░░░░░░░▄▄▄▀▀▀▄▄███▄░░░░░░░░░░░░░░
░░░░░▄▀▀░░░░░░░▐░▀██▌░░░░░░░░░░░░░
░░░▄▀░░░░▄▄███░▌▀▀░▀█░░░░░░░░░░░░░
░░▄█░░▄▀▀▒▒▒▒▒▄▐░░░░█▌░░░░░░░░░░░░
░▐█▀▄▀▄▄▄▄▀▀▀▀▌░░░░░▐█▄░░░░░░░░░░░
░▌▄▄▀▀░░░░░░░░▌░░░░▄███████▄░░░░░░
░░░░░░░░░░░░░▐░░░░▐███████████▄░░░
░░░░░le░░░░░░░▐░░░░▐█████████████▄
░░░░toucan░░░░░░▀▄░░░▐█████████████▄ 
░░░░░░has░░░░░░░░▀▄▄███████████████ 
░░░░░arrived░░░░░░░░░░░░█▀██████░░\e[m\n'

printf "$msg"

name="$1"

while [[ -z $name ]] || [[ $name =~ [A-Z] ]]
do
    printf "Please enter a name for your app in all lowercase letters: "
    read
    name="$REPLY"
done

printf "Would you like to install \e[32mAxios\e[m [y/n]: "
read axios

printf "Would you like to install \e[32mReact-Icons\e[m [y/n]: "
read icons

printf "Would you like to install \e[32mHeadlessUI\e[m [y/n]: "
read headless

printf 'Would you like to install \e[32mReact-Router\e[m [y/n]: '
read router

# CREATE REACT APP AND CD INTO DIR

npx create-react-app $name
cd $name

# OPTIONALLY INSTALL HEADLESS UI AND REACT ROUTER

if [[ $axios =~ ^[Yy]$ ]]
    then npm install axios
fi

if [[ $icons =~ ^[Yy]$ ]]
    then npm install react-icons --save
fi

if [[ $headless =~ ^[Yy]$ ]]
    then npm install @headlessui/react
fi

if [[ $router =~ ^[Yy]$ ]]
    then npm install react-router-dom
fi

# INSTALL TAILWIND AND CRACO

npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
npm install @craco/craco

# UPDATE package.json 

sed -i '' 's/react-scripts start/craco start/g' package.json
sed -i '' 's/react-scripts build/craco build/g' package.json
sed -i '' 's/react-scripts test/craco test/g' package.json

# CREATE craco.config.js AND ADD TEXT

echo -e "// craco.config.js\nmodule.exports = {\n    style: {\n       postcss: {\n           plugins: [\n              require('tailwindcss'),\n               require('autoprefixer'),\n           ],\n        },\n    },\n}" > craco.config.js

# CREATE tailwind.config.js AND UPDATE TEXT

npx tailwindcss-cli@latest init
echo -e "// tailwind.config.js\nmodule.exports = {\n  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],\n  darkMode: false, // or 'media' or 'class'\n  theme: {\n    extend: {},\n  },\n  variants: {\n    extend: {},\n  },\n  plugins: [],\n}" > tailwind.config.js

# UPDATE App.css WTIH @tailwind LINES

echo '@tailwind base;' > ./src/App.css
echo '@tailwind components;' >> ./src/App.css
echo '@tailwind utilities;' >> ./src/App.css

# UPDATE index.html

sed -i '' 's/<body>/<body class="bg-gray-900 text-white">/g' ./public/index.html

# UPDATE App.js

echo 'import "./App.css";' > ./src/App.js
echo -e '\n' >> ./src/App.js
echo 'const App = () => {' >> ./src/App.js
echo '    return (' >> ./src/App.js
echo '        <div>' >> ./src/App.js
echo '            <header>' >> ./src/App.js
echo '                <h1 className="text-3xl text-blue-400 p-4">Tailwind React App</h1>' >> ./src/App.js
echo '            </header>' >> ./src/App.js
echo '        </div>' >> ./src/App.js
echo '    );' >> ./src/App.js
echo -e '}\n' >> ./src/App.js
echo 'export default App;' >> ./src/App.js

 # Remove create-react-app garbage
rm ./src/logo.svg
rm ./src/reportWebVitals.js
rm ./src/index.css

sed -i '' '/import reportWebVitals/d' ./src/index.js
sed -i '' '/reportWebVitals()/d' ./src/index.js
sed -i '' '/index.css/d' ./src/index.js

mkdir ./src/components
mkdir ./src/services
touch ./src/services/DataService.js

# OPEN IN INTELLIJ AND START APP
idea .
npm start
